name: alphajudge
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.26
  - biopython>=1.83
  - scipy
  - pip
  - pytest
  - pytest-xdist
  - pip:
    - git+https://github.com/maurerv/pyzernike
    - -e .
